import math

Ceil=math.ceil(4.1)
print(Ceil)
Floor=math.floor(4.8)
print(Floor)
Trunc=math.trunc(3.9)
print(Trunc)
positive_value=math.fabs(-5)
print(positive_value)
factorial=math.factorial(5)
print(factorial)
Is_those_near_value=math.isclose(0.1+0.2, 0.3)
print(Is_those_near_value)
factor=math.gcd(48, 18)
print(factor)
multiplies=math.lcm(12, 15)
print(multiplies)
copysign=math.copysign(3, -1) 
print(copysign)
reminder=math.fmod(20, 6)
print(reminder)
reminder=math.remainder(20, 6)
print(reminder)

exponent=math.exp(2)  #  e^x 
print(exponent)
exponent1=math.expm1(1)
print(exponent1)
log=math.log(10)
print(log)
log10=math.log10(3)
print(log10)
log2=math.log2(3)
print(log2)
power=math.pow(3,4)
print(power)
sqrt=math.sqrt(16)
print(sqrt)
sin=math.sin(1)
print(sin)
cos=math.cos(0)
print(cos)
pi =math.pi
print(pi)
isqrt=math.isqrt(43)
print(isqrt)
print()
multiplies_of_list=math.prod([32,2,2,3,2,3])
print(multiplies_of_list)
distance_between_two_points=math.dist((1,3),(4,2))
print(distance_between_two_points)
# number=math.nan(23)
# print(number)
# distance between x and y by hypot
between=math.hypot(4,89)
print(between)